name = "zontromontro-landing"
main = "workers-site/index.js"
compatibility_date = "2023-04-23"
workers_dev = true

# Production environment (default)
routes = [
  { pattern = "zontromontro.com", custom_domain = true },
  { pattern = "www.zontromontro.com", custom_domain = true }
]

# Staging environment
[env.staging]
name = "zontromontro-landing-staging"
routes = [
  { pattern = "staging.zontromontro.com", custom_domain = true }
]

[site]
bucket = "."
include = [
  "*.html",
  "*.css", 
  "*.js",
  "Abstract Arts/**/*",
  "Logo/**/*"
]
exclude = [
  "node_modules", 
  "workers-site", 
  "package.json", 
  "package-lock.json", 
  "wrangler.toml",
  ".git",
  ".gitignore",
  "Design_Reference",
  "v1.zip"
]
